name: Publish Docs

on:
  workflow_dispatch: # allow manual runs
  push:
    branches:
      - docs  # == main
    paths: # avoid unnecessary builds
      - docs/**
      - book.toml
      - .github/workflows/docs.yml

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false # skip any intermediate builds but let finish

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.40
    steps:
      - uses: actions/checkout@v4
      - name: Install mdBook
        run: curl -sSL "https://github.com/rust-lang/mdBook/releases/download/v$MDBOOK_VERSION/mdbook-v$MDBOOK_VERSION-x86_64-unknown-linux-gnu.tar.gz" | tar -xz --directory /home/runner/.cargo/bin
      - id: pages
        uses: actions/configure-pages@v5
      - run: mdbook build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./book
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
